// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBvwvrnF4vCI-KaegDe7U4CBbaZTRRlso',
    appId: '1:500224573306:web:57502d4b826b94a581a0c3',
    messagingSenderId: '500224573306',
    projectId: 'student-directoryapp',
    authDomain: 'student-directoryapp.firebaseapp.com',
    storageBucket: 'student-directoryapp.firebasestorage.app',
    measurementId: 'G-JT3NC2TWJT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzE_zZv3MkRQGyAIvVWHTQtRH3G4Fr3ps',
    appId: '1:500224573306:android:140f008db07ab5e381a0c3',
    messagingSenderId: '500224573306',
    projectId: 'student-directoryapp',
    storageBucket: 'student-directoryapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0RuVgdTzIKV80U8WTKhkXETkt6XKeGBE',
    appId: '1:500224573306:ios:3c31f9b5eef157d481a0c3',
    messagingSenderId: '500224573306',
    projectId: 'student-directoryapp',
    storageBucket: 'student-directoryapp.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectory',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0RuVgdTzIKV80U8WTKhkXETkt6XKeGBE',
    appId: '1:500224573306:ios:3c31f9b5eef157d481a0c3',
    messagingSenderId: '500224573306',
    projectId: 'student-directoryapp',
    storageBucket: 'student-directoryapp.firebasestorage.app',
    iosBundleId: 'com.example.studentDirectory',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBvwvrnF4vCI-KaegDe7U4CBbaZTRRlso',
    appId: '1:500224573306:web:bc54f9b1ca4233ad81a0c3',
    messagingSenderId: '500224573306',
    projectId: 'student-directoryapp',
    authDomain: 'student-directoryapp.firebaseapp.com',
    storageBucket: 'student-directoryapp.firebasestorage.app',
    measurementId: 'G-8M3F3L4HRZ',
  );
}
